---

- name: MySQL | Copy MySQL service config
  template:
    src: mysql.service.j2
    dest: /lib/systemd/system/mysql.service
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: 0755
  notify: restart mysql

- name: MySQL | Copy global MySQL configuration
  template:
    src: my.cnf.j2
    dest: "{{ mysql_config_file }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: 0600
  notify: restart mysql

- name: MySQL | Ensure datadir exists
  file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"

- name: MySQL | Trying to initialize datadir
  command: /usr/sbin/mysqld --initialize-insecure --user={{ mysql_user }}
  ignore_errors: "yes"
  changed_when: false

- name: MySQL | Flush handlers to restart MySQL after previous initialization
  meta: flush_handlers

- name: MySQL | Ensure MySQL is started and enabled on boot
  service:
    name: mysql
    state: started
    enabled: "yes"
- name: MySQL | Flush handlers to restart MySQL after previous initialization
  meta: flush_handlers
